### PR TITLE
Automatically color new pulls

### PR DESCRIPTION
**Pull request by Urtgard**
Issue #114

### CODE REVIEW

**Comment by Nnoggie** [comment]
I merged this into a new branch, so the work and tests can continue there. Please commit the next changes to that new branch. The feature looks very nice, just need to test and think about a few different use cases.

The option "Use bright colors" should be on by default to increase visibility in my opinion.
Live Mode sync needs to be implemented and tested (i will take care of this).

**Comment by Urtgard** [comment]
Yes, visibility is better with "Use bright colors". I didn't make it a default setting to match the current default color.

Did only a quick test with Live Mode. One thing I didn't think about: What should happen if the group uses different color settings?
Use the settings from the player that started the Live Mode? Seperate Live Mode settings everyone can edit?

**Comment by Nnoggie** [comment]
The way i usually handled these issues is by handling stuff on a per-preset basis as in store the values that could be changed in the preset data. I'm not sure if that is the right way to go here because everytime you import a preset you would automatically import the color settings of that preset.

**Comment by Nnoggie** [comment]
Maybe seperate live mode settings that are stored in the preset instead of global db is the answer here.
This way the person that started the session will decide which settings the live mode will start with and everyone would also be able to edit these settings.

**Comment by Urtgard** [comment]
> Maybe seperate live mode settings that are stored in the preset instead of global db is the answer here.
> This way the person that started the session will decide which settings the live mode will start with and everyone would also be able to edit these settings.

Yes that's what I meant.

What about importing presets? In my opinion it would be better to update the colors according to the users settings. Else you end up with a different color scheme for every preset. Not something I would enjoy.

**Pull request merged**
