### PR TITLE
automatic coloring finalized

### PR DESCRIPTION
**Pull request by Stinth**
- automatic coloring now toggleable from default interface
- now accessing color settings through right-click menu on pullbuttons
- now disables local color blind checkbox when auto coloring is off

### CODE REVIEW

**Comment by Nnoggie** [comment]
- db.numberCustomColors seems to be nil on my first load, error at MethodDungeonTools.lua line 3262 
```
1x ...ider\libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua:164: Usage: <unnamed>:SetValue(value, [treatAsMouseEvent])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetValue'
[string "@!!!MethodInternalRaider\libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua"]:164: in function `SetValue'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.0.lua"]:3262: in function `MakeCustomColorFrame'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.0.lua"]:4675: in function <...aceMethodDungeonTools\MethodDungeonTools.lua:4608>
[string "@MethodDungeonTools\MethodDungeonTools-3.0.0.lua"]:543: in function `ShowInterface'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.0.lua"]:34: in function `OnClick'
[string "@BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:144: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
errorString = "...ider\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:164: Usage: <unnamed>:SetValue(value, [treatAsMouseEvent])"
isSimple = nil
hookedErrorHandeler = <function> defined @!BugGrabber\BugGrabber.lua:294
```
- you define a global ColorPicker at MethodDungeonTools.lua line 3291 - this should be local as it is not used outside of this scope as far as i can tell
- more errors regarding saved variables - comparing to the current master it seems the default saved variables are not the same?

**Comment by Stinth** [comment]
db.numberCustomColors should no longer exist and should now be 
db.colorPaletteInfo.numberCustomColors
Will investigate why that error is thrown.
the variable ColorPicker should indeed be local, the commit 22c8156 should have fixed that, I'll investigate why that isn't the case.

**Comment by Nnoggie** [comment]
the error was on my end (someone might have not pressed "pull")

**Comment by Nnoggie** [comment]
Okay, so no more errors after actually pulling your branch, but the automatic coloring does not seem to work even when turning automatic coloring off and back on or pressing "apply to preset"

**Comment by Stinth** [comment]
I re-commented the lines below "TODO" in MethodDungeonTools.lua , I realise now that probably wasn't a great idea. That should hopefully fix it?

**Comment by Stinth** [comment]
Seeing you start that key made me consider if there should be an easier way to "Apply to preset", perhaps through the right click menu. Instead of having the open the window and click the button.

**Comment by Nnoggie** [comment]
The "Apply to preset" button and the context menu entry "Colorize Preset" should enable automatic coloring when not enabled.

**Comment by Stinth** [comment]
The above commits should enable the desired toggling of automatic coloring in the mentioned instances.

**Comment by Nnoggie** [comment]
looking good!

**Pull request merged**
